# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  # vmImage: ubuntu-latest
  name: Default

variables:
  USER_PASSWORD: nguyenbach
stages:
  - stage: Build
    displayName: Build and Test
    jobs:
      - job: BuildJob
        displayName: Build Job
        steps:
          - bash: |
              echo $(pwd)
            workingDirectory: $(System.DefaultWorkingDirectory)
          - task: CmdLine@2
            displayName: Install newman
            inputs: 
              - script: 'echo $(pwd)'
              - script: 'echo $(USER_PASSWORD) | sudo -S npm install -g newman'
              - script: 'echo $(newman --version)'
            workingDirectory: $(System.DefaultWorkingDirectory)
          