# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  # vmImage: ubuntu-latest
  name: Default

stages:
  - stage: Build
    displayName: Build and Test
    jobs:
      - job: BuildJob
        displayName: Build Job
        steps:
          - bash: |
              echo $(pwd)
          - task: CmdLine@2
            displayName: Install newman
            inputs: |
              pwd
            