stages:
- stage: DeployStage
  displayName: Deploy to Environment
  jobs:
  - deployment: DeployJob
    displayName: Deploy Job
    pool: Default
    environment: 
      name: bachtn-env  # Ensure this matches the environment name in Azure DevOps
      resourceType: virtualMachine  # Or 'kubernetes' for Kubernetes environments
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none  # Assuming no code checkout is needed for the deployment script
          - script: echo Deploying to $(environment.name)
            displayName: 'Deploy Script'
          - script: echo $(env)
            displayName: 'Show env'